# Datei: 17-postgres/compose.yaml
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: geonames
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: info@dockerbuch.info
      PGADMIN_DEFAULT_PASSWORD: geheim

volumes:
  pgdata:
  pgadmindata:
