# Datei: cms-examples/04-joomla/compose.yaml
services:
  joomla:
    image: joomla:apache
    ports:
      - 8080:80
    volumes:
      - webdata:/var/www/html
    environment:
      JOOMLA_DB_HOST: mariadb
      JOOMLA_DB_NAME: dockerbuch
      JOOMLA_DB_USER: dockerbuch
      JOOMLA_DB_PASSWORD: chohbaeB3ooY90oyah4iech

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: eengi7suXeut
      MYSQL_DATABASE: dockerbuch
      MYSQL_USER: dockerbuch
      MYSQL_PASSWORD: chohbaeB3ooY90oyah4iech

volumes:
  webdata:
