# Datei: 06-wordpress/compose.yaml
services:
  db:
    image: mariadb:latest
    volumes:
      - vol-db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: geheim
    restart: always
  
  wordpress:
    image: wordpress:latest
    volumes:
      - vol-www:/var/www/html/wp-content
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_PASSWORD: geheim
    restart: always

volumes:
  vol-www:
  vol-db: