# Datei: 15-mariadb-init/compose.yaml
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: beispiel_datenbank
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d